### ISSUE TITLE
Missing test dependency?

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-python#1]
```
$ make test
nosetests
make: nosetests: No such file or directory
make: *** [test] Error 1
```

I fixed this by adding `nose` to https://github.com/bearburger/twingly-search-api-python/blob/263fe1c0c8716eaf6bee67c5a7d891cacfe88697/test_requirements.txt is that the way to go?

**Comment by bearburger** [comment]
Sorry. My bad. Yes your solution is right. `nose` is installed by default on TravisCI and I forgot that it is optional.
