### ISSUE TITLE
Convert query start and end time to UTC

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-python#16]
The API uses UTC, so we can help the user by converting the supplied  `start_time` and `end_time` to UTC, so the user doesn't have to think about it.

References
- https://github.com/twingly/twingly-search-api-ruby/issues/43
- https://github.com/twingly/twingly-search-api-ruby/pull/46

**Comment by roback** [comment]
Python has two "types" of datetime objects, one with and one without timezone information. The one without timezone seems to be the default:

``` python
>>> print datetime.datetime.strptime("2016-01-01 10:11:50 UTC", "%Y-%m-%d %H:%M:%S %Z").tzinfo
None
>>> print datetime.datetime.now().tzinfo
None
```

How should we treat datetimes without timezone? Issue a warning and interpret it as UTC?

**Comment by dentarg** [comment]
I think we should require the timezone information, so we can make a correct conversion. I don't think we have that many (if any) users of this client yet, so we won't be breaking anyones expectations.

**Comment by dentarg** [comment]
This is kinda strange though

``` python
>>> print datetime.datetime.utcnow().tzinfo
None
```

Is it a lot of work to use date and time with timezone information in Python? Hmm... we also want it to be easy to use the client, but by requiring timezone info we might make it harder.

**Comment by roback** [comment]
I think the first of my tests above is weird too. I explicitly added `UTC` to the date, but `.tzinfo` is `None`.

**Comment by dentarg** [comment]
https://docs.python.org/2/library/datetime.html#datetime.tzinfo is a good read

> An object of type `time` or `datetime` may be naive or aware.

Good distinction. Now on to how to use it...

[`datetime.now([tz])`](https://docs.python.org/2/library/datetime.html#datetime.datetime.now) can take "an instance of a class `tzinfo` subclass" as argument...

...but it seems like you have to create that class yourself, see examples at https://docs.python.org/2/library/datetime.html#tzinfo-objects. So it seems like you have to work a bit.

http://stackoverflow.com/questions/17976063/how-to-create-tzinfo-when-i-have-utc-offset suggests

> If you can, take a look at the excellent [dateutil package](https://labix.org/python-dateutil) instead of implementing this yourself.

Could be worth looking into. Perhaps it's enough having examples using dateutil.

**Comment by dentarg** [comment]
> Perhaps it's enough having examples using dateutil.

And our tests :)

**Comment by roback** [comment]
I saw that [`pytz`](http://pytz.sourceforge.net/) was mentioned in a few places too.

**Comment by dentarg** [comment]
Yeah, that seems good too, looks like that's what django uses. I guess these library creates general Python objects so the user could choose to use any of them?

**Comment by roback** [comment]
We have to add one of the above packages as a dependency since we should include the timezone in `Post#published` and `Post#indexed`: https://github.com/twingly/twingly-search-api-python/blob/23445a4c65f0a60f63b6c3490f605d4e0b0b8486/twingly_search/post.py#L44-L45

**Comment by dentarg** [comment]
Yeah, that's true.
