### ISSUE TITLE
Multiple languages throws exception

### ISSUE THREAD

**Issue by wkoot** [twingly/twingly-search-api-python#29]
Using multiple languages with the pipe separator throws generic exception.

```
>>> query.pattern = 'site:*.be'
>>> query.language = 'nl|fr'
>>> query.start_time = datetime.datetime(2016, 6, 20, 15, 0, 0)
>>> result = query.execute()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "lib/python2.7/site-packages/twingly_search/query.py", line 76, in execute
    return self.client.execute_query(self)
  File "lib/python2.7/site-packages/twingly_search/client.py", line 63, in execute_query
    return Parser().parse(response_body)
  File "lib/python2.7/site-packages/twingly_search/parser.py", line 27, in parse
    raise TwinglyServerException(e)
TwinglyServerException: no element found: line 1, column 0
```

**Comment by walro** [comment]
Actually, this should be covered already as seen as in one of our tests: https://github.com/twingly/twingly-search-api-python/blob/c0609a3a5d0e7df2e15a2a86e4fa53938d36fbfe/tests/test_parser.py#L38-L44

Mind sharing your query?

**Comment by wkoot** [comment]
```
query.pattern = 'site:*.be'
query.language = 'nl|fr'
query.start_time = datetime.datetime(2016, 6, 20, 15, 0, 0)
```

Edit: Ah indeed, changing language to only a single value does the trick. Can I pass a list instead?

**Comment by dentarg** [comment]
@wkoot try with only one language `query.language = 'nl'` to see if that works

**Comment by wkoot** [comment]
Yeah it works. How do I pass multiple languages without doing multiple calls?

**Comment by walro** [comment]
The API is admittedly a bit confusing when it comes to languages. Under the hood the `query.language` sets a query parameter which only support one language a time. So `query.pattern` to the rescue, try `site:*.be lang:nl|fr` and omit setting `query.language`.

**Comment by wkoot** [comment]
Cool, works
