### ISSUE TITLE
Name in twingly.spec

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-python#3]
Not a Python expert, so bare with me. But shouldn't name be `twingly-search` here: https://github.com/bearburger/twingly-search-api-python/blob/263fe1c0c8716eaf6bee67c5a7d891cacfe88697/twingly.spec#L3 ?

**Comment by dentarg** [comment]
and perhaps the file should be named `twingly-search.spec` :)

**Comment by bearburger** [comment]
Sadly, but Python can't use names with dashes. Well it can but this is [bad practice](http://stackoverflow.com/questions/7583652/python-module-with-a-dash-or-hyphen-in-its-name). There is similar descisions made in other packages that has names with multiple words, i.e. https://pypi.python.org/pypi/django-deep-collector/ imported as `deep_collector`.

I thought about `twingly` package with `search` submodule so user can load like `from twingly.search import client` but in this case module should be named as `twingly` in PyPI. If you prefer this way it's not hard to update library structure.

**Comment by walro** [comment]
Ah I see. Let me try to phrase it an another way, the package https://pypi.python.org/pypi/django-deep-collector/ is imported as `deep_collector`, but the "PyPi name" of it seems to be `django-deep-collector`, what decides the PyPi name? :) I thought the `.spec` file did that, but I have never published to PyPi.

**Comment by bearburger** [comment]
Package name that will be used on PyPI is set in `setup.py`. PyPI name doesn't affect library itself as PyPI is just storage for archives that built on your machine.

**Comment by dentarg** [comment]
hmm what is the `.spec` file used for? :)

**Comment by bearburger** [comment]
You will need it in case if you will decide to create native packages for Linux (*.deb, *.rpm).

**Comment by walro** [comment]
Thanks for the help @bearburger, closing.
