### ISSUE TITLE
Update Python client to Search API v3 [$100]

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-python#31]
Update the client to use the new [Blog Search API v3](https://developer.twingly.com/resources/search/).

Notable changes from the previous version of the Blog Search API are listed under https://developer.twingly.com/resources/search#changes-from-previous-version.

The ruby client was updated in https://github.com/twingly/twingly-search-api-ruby/pull/65, which can be used as help. Some XML fixtures can also be copied from there if needed.

If possible, try to keep all classes/methods/properties backwards compatible with the previous version of the client by marking methods as deprecated. Similar to what was done in the Ruby client.

**Comment by dentarg** [comment]
If you are considering solving this issue, you might be interested in also solving one or more of the following issues (they also have bounties from https://www.bountysource.com/)

* https://github.com/twingly/twingly-search-api-dotnet/issues/32
* https://github.com/twingly/twingly-search-api-php/issues/22
* https://github.com/twingly/twingly-search-api-java/issues/29

**Comment by dentarg** [comment]
@bearburger @xSAVIKx @amironoff anyone of you interested in the bounty here? 🤑

**Comment by dentarg** [comment]
Register (for free) at https://app.twingly.com/ to get an Blog Search API key to use when developing and testing (make sure it isn't recorded in any fixture)
